### ISSUE TITLE
Header matrix in check is not reflecting the filtered date range values

### ISSUE THREAD

**Issue by aliasgerkw** [checkly/public-roadmap#85] opened 2020-10-28 14:18 UTC
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
Lets say If I want to know the matrix values for previous month. On applying date range filter only the graph is changing but the values in header are still the same. 

**Describe the solution you'd like**
On applying date filter above values should change.

**Describe alternatives you've considered**
NA

**Additional context**
<img width="1176" alt="Screenshot 2020-10-28 at 7 45 48 PM" src="https://user-images.githubusercontent.com/51911147/97448328-8e499180-1956-11eb-9039-31947feca125.png">

**Comment by tnolet** [comment] 2020-10-29 21:48
@aliasgerkw thanks for the suggestion. This works "as designed". We are working in the background on making some big changes to how we store and aggregate data over longer ranges. Once we have shipped this we can "go crazy" with dynamic ranges and calculate the values. Specifically percentiles over long time ranges is a hard CS problem.

For now, the summary is really the summary. A predefined snapshot that we can load very quickly.

**Comment by aliasgerkw** [comment] 2020-10-30 05:17
Thanks @tnolet Will look forward with more reporting options.

**Comment by tnolet** [comment] 2021-01-07 09:11
@aliasgerkw I'm closing this ticket as it is not a bug. When reporting lands, you will have more fine grained access percentile data over arbitrary time ranges.

**Closed by tnolet** 2021-01-07 09:11 UTC
Labels: Reporting
